services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fastmail_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/posstgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  pgdata: